<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page import="timeclock.scheduling.ShowSchedules"%>
<%-- Your corrected ShowSchedules class --%>
<%-- JSTL taglib removed --%>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Schedule Management</title>
<link rel="stylesheet" href="css/scheduling.css?v=12">
<link rel="stylesheet" href="css/navbar.css">
<%-- Link to scheduling.css, increment version --%>
</head>
<body>
	<div class="parent-container">
	<%@ include file="/WEB-INF/includes/navbar.jspf" %>
		<h1>Schedule Management</h1>

		<div class="top-message">To Edit or Delete... First Select a Row</div>

		<div class="table-container">
			<table id="schedulesTable" class="schedules">
				<%-- Ensure ID is correct for JS --%>
				<thead>
					<tr>
				<thead>
					<tr>
						<th>Schedule Name</th>
						<%-- Keep left-aligned --%>
						<th class="center-text">Start Shift</th>
						<th class="center-text">Start Lunch</th>
						<th class="center-text">End Lunch</th>
						<th class="center-text">End Shift</th>
						<th>Days Scheduled</th>
						<%-- Keep left-aligned? --%>
						<th class="center-text">Auto Lunch</th>
						<th class="center-text">Hours Required</th>
						<th class="center-text">Lunch Length</th>
						<th class="center-text">Work Schedule</th>
					</tr>
				</thead>
				<tbody>
					<%-- Output rows generated by the corrected ShowSchedules.java --%>
					<%= ShowSchedules.showSchedules() %>
				</tbody>
			</table>
		</div>

		<%-- Buttons for Add/Edit/Delete --%>
		<div id="button-container">
			<button type="button" id="addScheduleButton">Add Schedule</button>
			<button type="button" id="editScheduleButton" disabled>Edit
				Schedule</button>
			<button type="button" id="deleteScheduleButton" disabled>Delete
				Schedule</button>
		</div>

		<%-- Hidden form for Delete action - CORRECT SERVLET NAME --%>
		<form action="AddEditAndDeleteSchedulesServlet" method="get"
			id="deleteScheduleForm">
			<input type="hidden" name="action" value="delete"> <input
				type="hidden" name="scheduleName" id="hiddenDeleteScheduleName"
				value="">
		</form>

	</div>
	<%-- End parent-container --%>

	<%-- =================================== --%>
	<%--        ADD SCHEDULE MODAL           --%>
	<%-- =================================== --%>
	<div id="addScheduleModal" class="modal">
		<div class="modal-content">
			<span class="close" id="closeAddModal">&times;</span>
			<h2>Add Schedule</h2>
			<%-- Form points to CORRECT servlet name --%>
			<form id="addScheduleForm" action="AddEditAndDeleteSchedulesServlet"
				method="post">
				<input type="hidden" name="action" value="add">

				<div class="form-item">
					<label for="addScheduleName">Schedule Name:</label> <input
						type="text" id="addScheduleName" name="scheduleName" required
						autofocus>
				</div>

				<div class="form-row">
					<div class="form-item">
						<label for="addShiftStart">Start Shift:</label> <input type="time"
							id="addShiftStart" name="shiftStart">
					</div>
					<div class="form-item">
						<label for="addShiftEnd">End Shift:</label> <input type="time"
							id="addShiftEnd" name="shiftEnd">
					</div>
				</div>
				<div class="form-row">
					<div class="form-item">
						<label for="addLunchStart">Start Lunch:</label> <input type="time"
							id="addLunchStart" name="lunchStart">
					</div>
					<div class="form-item">
						<label for="addLunchEnd">End Lunch:</label> <input type="time"
							id="addLunchEnd" name="lunchEnd">
					</div>
				</div>

				<div class="form-item">
					<label>Days Worked:</label>
					<div class="checkbox-group">
						<span class="styled-checkbox"> <input type="checkbox"
							id="addDaySun" name="days" value="Sun"> <label
							for="addDaySun">Sun</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="addDayMon" name="days" value="Mon"> <label
							for="addDayMon">Mon</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="addDayTue" name="days" value="Tue"> <label
							for="addDayTue">Tue</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="addDayWed" name="days" value="Wed"> <label
							for="addDayWed">Wed</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="addDayThu" name="days" value="Thu"> <label
							for="addDayThu">Thu</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="addDayFri" name="days" value="Fri"> <label
							for="addDayFri">Fri</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="addDaySat" name="days" value="Sat"> <label
							for="addDaySat">Sat</label>
						</span>
					</div>
				</div>

				<div class="form-row">
					<div class="form-item auto-lunch-toggle-group">
						<span class="styled-checkbox"> <input type="checkbox"
							id="addAutoLunch" name="autoLunch" value="true"> <label
							for="addAutoLunch">Auto Lunch</label>

						</span>
					</div>
					<div class="form-item">
						<label for="addHoursRequired">Hours Required:</label> <input
							type="number" id="addHoursRequired" name="hoursRequired" min="0"
							max="24" step="1" placeholder="e.g., 8" required disabled>
					</div>
					<div class="form-item">
						<label for="addLunchLength">Lunch Length (mins):</label> <input
							type="number" id="addLunchLength" name="lunchLength" min="0"
							max="90" step="1" placeholder="e.g., 30" required disabled>
					</div>
				</div>

				<div class="form-item">
					<label for="addWorkSchedule">Work Schedule Type:</label> <select
						id="addWorkSchedule" name="workSchedule">
						<option value="Full Time" selected>Full Time</option>
						<option value="Part Time">Part Time</option>
						<option value="Temporary">Temporary</option>
					</select>
				</div>

				<div class="button-row">
					<button type="submit" class="submit-btn">Submit</button>
					<button type="button" id="cancelAdd" class="cancel-btn">Cancel</button>
				</div>
			</form>
		</div>
	</div>

	<%-- =================================== --%>
	<%--        EDIT SCHEDULE MODAL          --%>
	<%-- =================================== --%>
	<div id="editScheduleModal" class="modal">
		<div class="modal-content">
			<span class="close" id="closeEditModal">&times;</span>
			<h2>Edit Schedule</h2>
			<%-- Form points to CORRECT servlet name --%>
			<%-- Uses IDs like editScheduleName, editShiftStart etc. --%>
			<form id="editScheduleForm" action="AddEditAndDeleteSchedulesServlet"
				method="post">
				<input type="hidden" name="action" value="edit"> <input
					type="hidden" name="originalScheduleName"
					id="hiddenEditOriginalName" value="">

				<div class="form-item">
					<label for="editScheduleName">Schedule Name:</label> <input
						type="text" id="editScheduleName" name="scheduleName" disabled>
				</div>

				<div class="form-row">
					<div class="form-item">
						<label for="editShiftStart">Start Shift:</label> <input
							type="time" id="editShiftStart" name="shiftStart">
					</div>
					<div class="form-item">
						<label for="editShiftEnd">End Shift:</label> <input type="time"
							id="editShiftEnd" name="shiftEnd">
					</div>
				</div>
				<div class="form-row">
					<div class="form-item">
						<label for="editLunchStart">Start Lunch:</label> <input
							type="time" id="editLunchStart" name="lunchStart">
					</div>
					<div class="form-item">
						<label for="editLunchEnd">End Lunch:</label> <input type="time"
							id="editLunchEnd" name="lunchEnd">
					</div>
				</div>

				<div class="form-item">
					<label>Days Worked:</label>
					<div class="checkbox-group">
						<%-- JS will check/uncheck these based on data --%>
						<span class="styled-checkbox"> <input type="checkbox"
							id="editDaySun" name="days" value="Sun"> <label
							for="editDaySun">Sun</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="editDayMon" name="days" value="Mon"> <label
							for="editDayMon">Mon</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="editDayTue" name="days" value="Tue"> <label
							for="editDayTue">Tue</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="editDayWed" name="days" value="Wed"> <label
							for="editDayWed">Wed</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="editDayThu" name="days" value="Thu"> <label
							for="editDayThu">Thu</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="editDayFri" name="days" value="Fri"> <label
							for="editDayFri">Fri</label>
						</span> <span class="styled-checkbox"> <input type="checkbox"
							id="editDaySat" name="days" value="Sat"> <label
							for="editDaySat">Sat</label>
						</span>
					</div>
				</div>

				<div class="form-row">
					<div class="form-item auto-lunch-toggle-group">
						<span class="styled-checkbox"> <input type="checkbox"
							id="editAutoLunch" name="autoLunch" value="true"> <label
							for="editAutoLunch">Auto Lunch</label>
						</span>
					</div>
					<div class="form-item">
						<label for="editHoursRequired">Hours Required:</label> <input
							type="number" id="editHoursRequired" name="hoursRequired" min="0"
							max="24" step="1" required>
						<%-- JS populates/disables --%>
					</div>
					<div class="form-item">
						<label for="editLunchLength">Lunch Length (mins):</label> <input
							type="number" id="editLunchLength" name="lunchLength" min="0"
							max="90" step="1" required>
						<%-- JS populates/disables --%>
					</div>
				</div>

				<div class="form-item">
					<label for="editWorkSchedule">Work Schedule Type:</label> <select
						id="editWorkSchedule" name="workSchedule">
						<option value="Full Time">Full Time</option>
						<option value="Part Time">Part Time</option>
						<option value="Temporary">Temporary</option>
					</select>
				</div>

				<div class="button-row">
					<button type="submit" class="submit-btn">Update</button>
					<button type="button" id="cancelEdit" class="cancel-btn">Cancel</button>
				</div>
			</form>
		</div>
	</div>

	<%-- Notification Modal --%>
	<div id="notificationModal" class="modal">
		<div class="modal-content">
			<span class="close" id="closeNotificationModal">&times;</span>
			<h2>Notification</h2>
			<p id="notificationMessage"></p>
			<div class="button-row" style="justify-content: center;">
				<button type="button" id="okButton">OK</button>
			</div>
		</div>
	</div>

	<%-- Link the External JavaScript file --%>
	<script src="${pageContext.request.contextPath}/js/scheduling.js?v=9"></script>
	<%-- Increment version --%>

</body>
</html>